alembic/operations/base.py

Fixes the wrong version position in `table_kwargs`. 
See: https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.batch_alter_table …

Fix typo in documentation

---

docs/build/naming.rst

Typo fix: appopriate -> appropriate in "The Importance of Naming Constraints".

Typo fix: appopriate -> appropriate.

---

docs/build/cookbook.rst

A fix for #753 was merged in November 2020 and [released in 1.5.0](https://alembic.sqlalchemy.org/en/latest/changelog.html#change-1.5.0-bug) in January 2021.
This updates the references to #753 in cookbook.rst to note that a fix for #753 has been released.
Alternatively, it may make sense to just delete the workarounds.

Update cookbook.rst references to #753

---

docs/build/autogenerate.rst

Thanks for this great project! I've been reading the documentation at https://alembic.sqlalchemy.org/en/latest/, and noticed what I believe is a mistake in the docs on `alembic revision --autogenerate`.
There is a literal Sphinx [`versionchanged` directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionchanged) in the section on comparing types (https://alembic.sqlalchemy.org/en/latest/autogenerate.html#comparing-types).
This pull request proposes a fix that will result in this being correctly rendered as a callout box.
I tested this by building the docs locally, and it seems to work as expected.
```shell
cd docs/builds
pip install -r requirements.txt
make clean html
```
I also searched for other issues like this with …

[docs] fix versionchanged directive in autogenerate docs

---

docs/build/batch.rst

Clarifies language about `ALTER` in the batch migrations docs.
I think the double use of "upon" in this phrase is not quite correct, and confused me when I first read it.
> the ALTER statement upon which relation schema migrations rely upon
This PR proposes changing that to
> the ALTER statement relational schema migrations rely upon.
- please include the issue number, and create an …

[doc] clarify ALTER language in batch docs

---

.gitignore

Fixes #824
Running `tox` produces a `/pysqlite_test_schema.db` file which has been added to `.gitignore`.
Add `/pysqlite_test_schema.db` to `.gitignore`. …

Add /pysqlite_test_schema.db to .gitignore

---

docs/build/tutorial.rst

It seems that latest version of alembic lists `async` as template
Add `async` template to `tutorial.rst`
Add `async` template to `tutorial.rst`
**Have a nice …

Add async as template to docs

---

docs/build/api/autogenerate.rst
docs/build/api/config.rst

Fix various typos under the doc/build/api section. Separate PR's, when time allows, will be pushed for other areas with typos.
This PR identified typos in the documentation using the codespell project with an updated dictionary from September 7th to locate the typos. Filters were used to avoid known "typos" such as selectin which are library-specific rather than actual typos.
X-Ref: https://github.com/codespell-project/codespell
- please include tests.   one line …

fix: typos in doc/build/api

---

docs/build/tutorial.rst

This PR adds information to the tutorial page regarding the `ALEMBIC_CONFIG` variable which was made available in b12f31b (and described in #608). This should hopefully make it more clear to first-time users what options are available for setting the path to the configuration file.
include a complete …

Update documentation about alembic configuration path

---

alembic/templates/async/alembic.ini.mako
alembic/templates/generic/alembic.ini.mako
alembic/templates/multidb/alembic.ini.mako
alembic/templates/pylons/alembic.ini.mako
docs/build/branches.rst
docs/build/tutorial.rst

I tried to improve docs regarding `version_path_separator` based on my experience with it.
**Have a nice day!**

Tweak docs about version_path_separator

---

alembic/templates/async/env.py
docs/build/cookbook.rst

Update the asyncio example cookbook doc, according to https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#synopsis-core, to include a call to dispose the engine.
Without this dispose call, my test case gets:
```
Task <Task pending name='Task-14' coro=<run_migrations_online() running at migrations/env.py:27> cb=[_run_until_complete_cb() at /python3-3.8.8/lib/python3.8/asyncio/base_events.py:184] created at /python3-3.8.8/lib/python3.8/asyncio/base_events.py:595> got Future <Future pending cb=[Protocol._on_waiter_completed()] created at /python3-3.8.8/lib/python3.8/asyncio/base_events.py:422> attached to a different loop
```
And it with it, everything seems to work.
EDIT: It was also missing in the async template, which I've also added.
- Good to go, no issue …

Add missing engine.dispose() call to the asyncio cookbook example.

---

.github/workflows/run-on-pr.yaml
.github/workflows/run-test.yaml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

docs/build/cookbook.rst

Fixes #1050 - Adds instructions for including an info object on a declarative table for [Don’t emit CREATE TABLE statements for Views](https://alembic.sqlalchemy.org/en/latest/cookbook.html#don-t-emit-create-table-statements-for-views).
- Please …

Fix #1050 - docs(cookbook): add note on including info object on declarative tables

---

alembic/op.pyi
alembic/operations/ops.py
tools/write_pyi.py

When escaping the `:` for `op.execute` if a normal string is used, you need to escape the backslash, eg. `'\\:colon_value'` or using a raw string. For the docs I feel it is nicer to show the raw string.

Update docstring to suggest raw string

---

setup.cfg

Python package metadata got additional link to Changelog.
Package urls got additional url for Changelog.
Order of links was also changed to go from the most general to the most specific:
-  Documentation
-  Changelog
-  Source
- Issue Tracker

setup.cfg Project Links: added Changelog + reorder

---

README.rst
alembic/config.py
alembic/op.pyi
alembic/operations/base.py
alembic/operations/ops.py
alembic/script/revision.py
docs/build/branches.rst
docs/build/changelog.rst
docs/build/cookbook.rst
docs/build/front.rst
docs/build/naming.rst
tests/test_autogen_composition.py
tests/test_autogen_diffs.py
tests/test_autogen_render.py
tests/test_batch.py
tests/test_config.py
tests/test_op.py
tests/test_oracle.py
tests/test_postgresql.py
tests/test_version_traversal.py

Fixes misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
The misspellings have been reported at https://github.com/jsoref/alembic/actions/runs/6141700632
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/alembic/actions/runs/6141700754
- please include the issue number, and create …

Spelling fixes

---

alembic/command.py

fix(command): `init --package` path display

---

alembic/operations/base.py
alembic/operations/ops.py

The constraint name parameter of create_foreign_key should be optional, but the batch function defined it as str instead of Optional[str].
Closes #1429 …

Fix type annotations in create_foreign_key

---

docs/build/tutorial.rst

Due ruff package update - `ruff <path>` has been removed. Use `ruff check <path>` instead.
Due ruff package update in new versions, command `ruff <path>` has been removed. Use `ruff check <path>` instead. Example in tutorial will be not work for new ruff versions

Update tutorial.rst for ruff post_write_hooks

---

docs/build/autogenerate.rst

During building of the docs, I got this warning:
> alembic/docs/build/autogenerate.rst:733: WARNING: Bullet list ends without a blank line; unexpected unindent. [docutils]
This also causes a small display issue, where the continuation of the line of the bullet point gets rendered as a new paragraph. This PR fixes the issue.

Docs: fix layout issue in autogenerate

---

alembic/autogenerate/compare.py

- the '%r' caused two single ticks like '' to show
- What we want is a single tick '
- This aligns now with the usage in other log statements
**Have a nice …

fix: remove double quotation marks in logs
